
version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # No volumes, keep DB inside container
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///app/bagofholding.db
    ports:
      - "3000:80"
      - "8001:8000"
    restart: unless-stopped



