"""create coins table

Revision ID: 27b98c692973
Revises: fix_container_charid_str
Create Date: 2025-09-15 16:25:18.051326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b98c692973'
down_revision: Union[str, Sequence[str], None] = 'fix_container_charid_str'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('source', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coins', 'source')
    # ### end Alembic commands ###
